[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
authors = ["Tomasz Kurcz", "Confio GmbH"]
license = "Apache-2.0"

[workspace.dependencies]
thiserror = "1"

stork = { path = "crates/stork", version = "0.1.0" }
