[changelog]
body = """
## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}

{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | striptags | trim | upper_first }}
{% for commit in commits %}
{%- if commit.scope -%}
- *({{commit.scope}})* {% if commit.breaking %}[**breaking**] {% endif %}{{ commit.message }}{%- if commit.links %} ({% for link in commit.links %}[{{link.text}}]({{link.href}}) {% endfor -%}){% endif %}
{% else -%}
- {% if commit.breaking %}[**breaking**] {% endif %}{{ commit.message }}
{% endif -%}
{% endfor -%}
{% endfor %}
"""
commit_parsers = [
    { message = "^feat", group = "<!-- 0 -->Added" },
    { message = "^changed", group = "<!-- 1 -->Changed" },
    { message = "^deprecated", group = "<!-- 2 -->Deprecated" },
    { message = "^fix", group = "<!-- 3 -->Fixed" },
    { message = "^sec", group = "<!-- 4 -->Security" },
    { message = "^docs", group = "<!-- 5 -->Documentation" },
    { message = "^test", group = "<!-- 6 -->Tests" },
]

[workspace]
git_tag_enable = false

[[package]]
name = "cw-storey"
git_tag_enable = true
