[package]
name = "mocks"
version = "0.1.0"
edition = "2021"
publish = false
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
storey-encoding.workspace = true
storey-storage.workspace = true
