[package]
name = "cw-storey"
description = "storey integration for CosmWasm"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
categories = { workspace = true }
keywords = { workspace = true }
version = "0.3.0"
edition = "2021"
license = { workspace = true }

[dependencies]
cosmwasm-std = "2"
serde = "1"

# TODO: temporary, remove after this is released:
# https://github.com/CosmWasm/cosmwasm/pull/2118
cosmwasm-std-new = { git = "https://github.com/CosmWasm/cosmwasm.git", rev = "553bdd6fc5cc9c74bebcba99a89c0c4334b8824d", package = "cosmwasm-std" }

storey = { workspace = true }
