on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'

jobs:
  run_if:
    if: startsWith(github.head_ref, 'release-pr/') && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: regular-${{ hashFiles('**/Cargo.lock') }}
      - name: Install cargo-release
        uses: taiki-e/install-action@v1
        with:
          tool: cargo-release
      - name: Build
        run: cargo release # stuff